name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting (flake8)
        run: flake8 app.py tests/

      - name: Check formatting (black)
        run: black --check app.py tests/

      - name: Run security checks (Bandit)
        run: bandit -r app.py

      - name: Run tests
        run: pytest -v

  docker:
    runs-on: ubuntu-latest
    needs: build-test-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t \${{ secrets.DOCKER_USERNAME }}/flask-calculator:latest .

      - name: Run container (smoke test)
        run: |
          docker run -d -p 5000:5000 --name calc \${{ secrets.DOCKER_USERNAME }}/flask-calculator:latest
          sleep 5
          curl --fail http://localhost:5000/health || exit 1

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push \${{ secrets.DOCKER_USERNAME }}/flask-calculator:latest

  notify:
    runs-on: ubuntu-latest
    needs: [docker]
    if: failure()
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: \${{ secrets.EMAIL_USER }}
          password: \${{ secrets.EMAIL_PASS }}
          subject: "CI/CD Pipeline Failed"
          to: \${{ secrets.NOTIFY_EMAIL }}
          from: "CI/CD Bot"
          body: "The pipeline has failed. Please check logs."

      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: \${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#FF0000'
          SLACK_MESSAGE: "🚨 CI/CD Pipeline failed! Check GitHub Actions logs."
